name: CI/CD Pipeline - Unit and Integration Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          cd app
          npm install

      
      - name: Create .env file
        run: |
          echo "VITE_GOOGLE_CALENDAR_API_KEY=${{ secrets.CALENDAR_API_KEY }}" >> app/.env
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> app/.env

      # No tests yet
      - name: Run placeholder tests
        run: |
          cd app
          npm test

    # add steps to deploy to vercel
